version: 2.1

executors:
  python36:
    docker:
      - image: circleci/python:3.6.5

commands:
  ditto-transform:
    description: Run Ditto in order to transform the base URL to https://pokeapi.co instead of localhost
    steps:
      - run: pip install --user -r requirements.txt
      - run:
          command: |
            ~/.local/bin/ditto transform \
              --base-url='https://pokeapi.co' \
              --src-dir=data \
              --dest-dir=_gen

jobs:
  test:
    executor: python36
    steps:
      - checkout
      - ditto-transform
  build-and-deploy:
    executor: python36
    steps:
      - checkout
      - ditto-transform
      - run: tar czf _gen.tar.gz _gen/*
      - store_artifacts:
          path: _gen.tar.gz
      - run: "curl -X POST --header \"Content-Type: application/json\" https://circleci.com/api/v1.1/project/github/PokeAPI/deploy/build?circle-token=$CIRCLECI_API_TOKEN"

workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      - test
      - build-and-deploy:
          requires:
            - test
          filters:
            branches:
              only: master
